function [A, Dcart] = build_pbc_bond_graph(species, frac_coords, lattice, scaleFactor, varargin)
%BUILD_PBC_BOND_GRAPH PBC-aware covalent bond graph using shared spatial search.
%
% [A, Dcart] = io.build_pbc_bond_graph(species, frac_coords, lattice, scaleFactor)
% [A, Dcart] = io.build_pbc_bond_graph(..., 'Verbose', tf, ...
%     'ProgressInterval', k, 'ReturnDcart', tf)
%
% Inputs
%   species       N x 1 cell/string array of element symbols
%   frac_coords   N x 3 fractional coordinates
%   lattice       3 x 3 direct lattice matrix
%                 Project convention:
%                     lattice vectors are rows
%                     cart = frac * lattice
%   scaleFactor   scalar multiplier on covalent-radius sum, default 1.20
%
% Optional name-value inputs
%   'Verbose'           logical, default false
%   'ProgressInterval'  positive integer, default 2500
%   'ReturnDcart'       logical, default false
%   'Method'            'auto'|'cell_list'|'bruteforce', default 'auto'
%
% Outputs
%   A       N x N sparse logical adjacency matrix
%   Dcart   N x N dense minimum-image Cartesian distance matrix if requested;
%           otherwise []
%
% Notes
%   - Candidate pairs are generated by:
%         geom.build_spatial_index
%         geom.query_pairs_within_cutoff
%   - Chemistry-specific bond acceptance is delegated to:
%         io.bond_graph_tools.is_bonded
%   - H-H pairs are ignored by io.bond_graph_tools.ignore_pair.
%   - Adjacency is sparse to avoid dense O(N^2) memory cost.

if nargin < 4 || isempty(scaleFactor)
    scaleFactor = 1.20;
end

p = inputParser;
addParameter(p, 'Verbose', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'ProgressInterval', 2500, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 1);
addParameter(p, 'ReturnDcart', false, @(x) islogical(x) && isscalar(x));
addParameter(p, 'Method', 'auto', @(x) ischar(x) || isstring(x));
parse(p, varargin{:});
opt = p.Results;

% -------------------------------------------------------------------------
% Validate and normalize inputs
% -------------------------------------------------------------------------

if isstring(species)
    species = cellstr(species(:));
elseif iscellstr(species)
    species = species(:);
else
    error('io:build_pbc_bond_graph:BadSpecies', ...
        'species must be a string array or cell array of character vectors.');
end

n = numel(species);

if ~isnumeric(frac_coords) || size(frac_coords, 1) ~= n || size(frac_coords, 2) ~= 3
    error('io:build_pbc_bond_graph:BadFracCoords', ...
        'frac_coords must be numeric N x 3 and match species.');
end

if ~isnumeric(lattice) || ~isequal(size(lattice), [3 3])
    error('io:build_pbc_bond_graph:BadLattice', ...
        'lattice must be a numeric 3 x 3 matrix.');
end

if ~isscalar(scaleFactor) || ~isfinite(scaleFactor) || scaleFactor <= 0
    error('io:build_pbc_bond_graph:BadScaleFactor', ...
        'scaleFactor must be a positive finite scalar.');
end

method = char(string(opt.Method));

switch method
    case {'auto', 'cell_list', 'bruteforce'}
        % ok
    otherwise
        error('io:build_pbc_bond_graph:BadMethod', ...
            'Method must be ''auto'', ''cell_list'', or ''bruteforce''.');
end

% Keep fractional coordinates wrapped for stable Cartesian generation and
% distance matrix construction.
frac_coords = frac_coords - floor(frac_coords);

if opt.Verbose
    fprintf('build_pbc_bond_graph: starting for %d atoms\n', n);
    tStart = tic;
end

if opt.ReturnDcart
    Dcart = zeros(n, n);
else
    Dcart = [];
end

if n == 0
    A = sparse(false(0, 0));
    return;
end

% -------------------------------------------------------------------------
% Precompute radii and global candidate cutoff
% -------------------------------------------------------------------------

radii = zeros(n, 1);

for i = 1:n
    radii(i) = io.bond_graph_tools.covalent_radius(species{i});
end

% Any accepted bond must satisfy:
%   d <= scaleFactor * (r_i + r_j)
% A safe global candidate cutoff is therefore:
%   scaleFactor * 2 * max(r_i)
maxBondCutoff = scaleFactor * (2 * max(radii));

% -------------------------------------------------------------------------
% Generate candidate pairs through shared geometry search
% -------------------------------------------------------------------------

cart_coords = frac_coords * lattice;

spatial = geom.build_spatial_index(cart_coords, struct( ...
    'isPeriodic', true, ...
    'cell', lattice, ...
    'method', method, ...
    'cutoff', maxBondCutoff));

pairs = geom.query_pairs_within_cutoff(spatial, maxBondCutoff, struct( ...
    'return_r', true, ...
    'return_dr', false, ...
    'return_full_idx', true));

nPairs = numel(pairs.i);

if opt.Verbose
    fprintf('build_pbc_bond_graph: candidate pairs within global cutoff = %d\n', nPairs);
end

% -------------------------------------------------------------------------
% Apply species-specific covalent-bond tests
% -------------------------------------------------------------------------

I = zeros(nPairs, 1);
J = zeros(nPairs, 1);

nKeep = 0;

for kk = 1:nPairs
    i = pairs.i(kk);
    j = pairs.j(kk);
    dij = pairs.r(kk);

    if io.bond_graph_tools.is_bonded(species{i}, species{j}, dij, scaleFactor)
        nKeep = nKeep + 1;
        I(nKeep) = i;
        J(nKeep) = j;
    end

    if opt.Verbose
        if mod(kk, opt.ProgressInterval) == 0 || kk == nPairs
            fprintf('  processed %d / %d candidate bond pairs\n', kk, nPairs);
        end
    end
end

I = I(1:nKeep);
J = J(1:nKeep);

A = sparse([I; J], [J; I], true, n, n);

% -------------------------------------------------------------------------
% Optional dense minimum-image distance matrix
% -------------------------------------------------------------------------

if opt.ReturnDcart
    for i = 1:(n - 1)
        df = frac_coords((i + 1):n, :) - frac_coords(i, :);
        df = df - round(df);

        dcart = df * lattice;
        d = sqrt(sum(dcart.^2, 2));

        Dcart(i, (i + 1):n) = d.';
        Dcart((i + 1):n, i) = d.';
    end
end

if opt.Verbose
    fprintf('build_pbc_bond_graph: accepted bonds = %d\n', nKeep);
    fprintf('build_pbc_bond_graph: finished in %.3f s\n', toc(tStart));
end

end