function test_builder_neighbor_selectors()
%TEST_BUILDER_NEIGHBOR_SELECTORS Verify same/side/skew selector behavior.

desc = local_make_selector_desc();

same = builder.select_same_stack_neighbor(desc, 1, ...
    'PerpTol', 1e-6, ...
    'Direction', 'either', ...
    'ShellTol', 1e-6);

assert(isequal(sort(same.match_table.molecule_id), [2; 3]), ...
    'Same-stack shell 1 should contain molecules 2 and 3.');

samePlus = builder.select_same_stack_neighbor(desc, 1, ...
    'PerpTol', 1e-6, ...
    'Direction', '+', ...
    'ShellTol', 1e-6);

assert(isequal(samePlus.match_table.molecule_id, 2), ...
    'Positive same-stack shell 1 should select molecule 2.');

sameShell2 = builder.select_same_stack_neighbor(desc, 2, ...
    'PerpTol', 1e-6, ...
    'Direction', '+', ...
    'ShellTol', 1e-6);

assert(isequal(sameShell2.match_table.molecule_id, 4), ...
    'Positive same-stack shell 2 should select molecule 4.');

side = builder.select_side_stack_neighbor(desc, 1, 1, ...
    'SameStackPerpTol', 1e-6, ...
    'Direction', 'either', ...
    'ShellTol', 1e-6, ...
    'VectorGroupTol', 1e-6);

assert(isequal(sort(side.match_table.molecule_id), [5; 6]), ...
    'Side-stack shell 1 member 1 should contain molecules 5 and 6.');

sidePlusMember2 = builder.select_side_stack_neighbor(desc, 1, 2, ...
    'SameStackPerpTol', 1e-6, ...
    'Direction', '+', ...
    'ShellTol', 1e-6, ...
    'VectorGroupTol', 1e-6);

assert(isequal(sidePlusMember2.match_table.molecule_id, 7), ...
    'Positive side-stack shell 1 member 2 should select molecule 7.');

skew = builder.select_skew_neighbor(desc, 1, ...
    'NormalTargetDeg', 72, ...
    'NormalTolDeg', 5, ...
    'Direction', 'either', ...
    'ShellTol', 1e-6);

assert(isequal(skew.match_table.molecule_id, 8), ...
    'Skew shell 1 should select molecule 8.');

skewShell2 = builder.select_skew_neighbor(desc, 2, ...
    'NormalTargetDeg', 72, ...
    'NormalTolDeg', 5, ...
    'Direction', 'either', ...
    'ShellTol', 1e-6);

assert(isequal(skewShell2.match_table.molecule_id, 9), ...
    'Skew shell 2 should select molecule 9.');

end

function desc = local_make_selector_desc()

% Descriptor rows:
%   2,3: same-stack shell 1 at +/-2 along stack axis
%   4:   same-stack shell 2 at +4
%   5,6: side-stack shell 1, member 1 at d_perp=[3 0 0], d_par +/-1
%   7:   side-stack shell 1, member 2 at d_perp=[3 0 0], d_par +2
%   8,9: skew candidates near 72 deg, distance shells 5 and 7

molecule_id = (2:9).';
is_complete = true(numel(molecule_id), 1);
n_sites = 4 * ones(numel(molecule_id), 1);

dr = [
    0  2 0
    0 -2 0
    0  4 0
    3  1 0
    3 -1 0
    3  2 0
    5  0 0
    7  0 0
];

stackAxis = [0 1 0];

d_par = dr * stackAxis.';
d_perp_vec = dr - d_par * stackAxis;
d_perp = sqrt(sum(d_perp_vec.^2, 2));
distance = sqrt(sum(dr.^2, 2));

normal = repmat([0 0 1], numel(molecule_id), 1);
normal_angle_deg = zeros(numel(molecule_id), 1);

normal_angle_deg(7) = 72;  % molecule 8
normal_angle_deg(8) = 72;  % molecule 9

desc = struct();
desc.reference_mol_id = 1;
desc.reference_site_indices = (1:4).';
desc.reference_com = [0 0 0];
desc.reference_normal = [0 0 1];
desc.stack_axis_hat = stackAxis;

desc.table = table( ...
    molecule_id, ...
    is_complete, ...
    n_sites, ...
    dr(:,1), dr(:,2), dr(:,3), ...
    dr(:,1), dr(:,2), dr(:,3), ...
    d_par, ...
    d_perp_vec(:,1), d_perp_vec(:,2), d_perp_vec(:,3), ...
    d_perp, ...
    distance, ...
    normal(:,1), normal(:,2), normal(:,3), ...
    normal_angle_deg, ...
    'VariableNames', { ...
        'molecule_id', ...
        'is_complete', ...
        'n_sites', ...
        'com_x', 'com_y', 'com_z', ...
        'dr_x', 'dr_y', 'dr_z', ...
        'd_par', ...
        'd_perp_x', 'd_perp_y', 'd_perp_z', ...
        'd_perp', ...
        'distance', ...
        'normal_x', 'normal_y', 'normal_z', ...
        'normal_angle_deg'});

end